# FINAL, CORRECTED docker-compose.yml
# This version aligns with your original, working setup.

services:
  cosyvoice:
    build:
      context: ..
      # Uses the new, minimal Dockerfile that does NOT download models.
      dockerfile: Docker/Dockerfile.cosyvoice
    platform: linux/arm64
    container_name: cosyvoice-api
    ports:
      - "8002:8000"
    volumes:
      # This is the most important part. It mounts your local, working models
      # into the container, which is how you had it working before.
      - ../Backend/CosyVoice/pretrained_models:/app/CosyVoice/pretrained_models:ro
    restart: unless-stopped
    networks:
      - app-network

  # --- VOICE SIMILARITY (DISABLED) ---
  # voice-similarity:
  #   build:
  #     context: ..
  #     dockerfile: Docker/Dockerfile.similarity
  #   platform: linux/arm64
  #   container_name: voice-similarity-api
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - pretrained_models_similarity:/app/pretrained_models
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  musetalk:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.musetalk
    platform: linux/arm64
    container_name: musetalk-api
    ports:
      - "8003:8000"
    environment:
      - PYTHONPATH=/app/MuseTalk
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pretrained_models_similarity: {}