# FINAL, COMPLETE, AND UNIFIED docker-compose.yml

services:
  cosyvoice:
    build:
      context: ..
      # This uses the Dockerfile that bakes the models into the image,
      # which we confirmed is the correct working pattern from your other branch.
      dockerfile: Docker/Dockerfile.cosyvoice
    platform: linux/arm64
    container_name: cosyvoice-api
    ports:
      - "8002:8000"
    # CRITICALLY, there is NO volume mount for models.
    # This was the key fix to prevent your local folder from causing the startup error.
    restart: unless-stopped
    networks:
      - app-network

  # --- VOICE SIMILARITY (DISABLED) ---
  # This entire section is commented out for future work, as you requested.
  #
  # voice-similarity:
  #   build:
  #     context: ..
  #     dockerfile: Docker/Dockerfile.similarity
  #   platform: linux/arm64
  #   container_name: voice-similarity-api
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - pretrained_models_similarity:/app/pretrained_models
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  musetalk:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.musetalk
    platform: linux/arm64
    container_name: musetalk-api
    ports:
      - "8003:8000"
    # FIX: These two lines solve the MuseTalk startup error ("ModuleNotFoundError").
    # They tell the container exactly where to run the code from and where to find the library.
    working_dir: /app/MuseTalk
    environment:
      - PYTHONPATH=/app/MuseTalk
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  # This is defined for the (disabled) voice-similarity service. It is harmless.
  pretrained_models_similarity: {}