version: '3.8'

services:
  openvoice: # You can keep this if you still want to experiment with it, or remove it
    build:
      context: .. 
      dockerfile: Docker/Dockerfile 
    container_name: docker-openvoice
    ports:
      - "8000:8000"
    volumes:
      - ../checkpoints_v2:/app/checkpoints_v2:ro 
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-network

  voice-similarity:
    build:
      context: .. 
      dockerfile: Docker/Dockerfile.similarity 
    container_name: docker-voice-similarity
    ports:
      - "8001:8001" 
    volumes:
      # This volume caches downloaded SpeechBrain models on your host
      - ./pretrained_models_similarity:/app/pretrained_models 
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-network

  # --- NEW CosyVoice Service ---
  cosyvoice:
    build:
      context: .. # Root of Magenta AI project
      dockerfile: Docker/Dockerfile.cosyvoice # Path to the new Dockerfile
    container_name: docker-cosyvoice
    ports:
      - "8002:8000" # Expose CosyVoice API on host port 8002, container port 8000
    volumes:
      # This volume caches the downloaded CosyVoice models on your host
      # The path inside the container should match where Dockerfile.cosyvoice downloads/expects them
      # which is /app/CosyVoice/pretrained_models
      - ./pretrained_cosyvoice_models:/app/CosyVoice/pretrained_models
    # If using GPU:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false # Good practice for Hugging Face tokenizers
      # Add any other environment variables CosyVoice might need
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Define named volumes for persistent model caches
volumes:
  pretrained_models_similarity:
  pretrained_cosyvoice_models: # Ensures models persist across container recreation